### ISSUE TITLE
There is a parse error.

### ISSUE THREAD

**Issue by codcodog** [inteleon/export-builder#1]
on php 5.4.16 ,  there is a parse error.
on inteleon/export-builder/src/Builders/ReportBuilder.php on line 19.
Here is the code: 
```
$this->addExportType('pdf', ReportPDF::class);
```
Evidently, use the key word `class` is not right for php 5.4.
Howerver, on my local machine, I use php 7 , there is no problem.

**Comment by codcodog** [comment]
On php manual, it says: 
Since PHP 5.5, the class keyword is also used for class name resolution. You can get a string containing the fully qualified name of the ClassName class by using ClassName::class. This is particularly useful with namespaced classes.
[class](http://php.net/manual/en/language.oop5.basic.php)

**Comment by dlnilsson** [comment]
Thank you for noticing this! We've updated tag [1.1.1](https://github.com/inteleon/export-builder/releases/tag/1.1.1) with changes and minimum required version of php is now 5.4.
